In [1]:
#numpy
import numpy as np
#pandas
import pandas as pd


In [2]:

# @hidden_cell
# The following code contains the credentials for a file in your IBM Cloud Object Storage.
# You might want to remove those credentials before you share your notebook.
credentials_1 = {
    'IAM_SERVICE_ID': 'iam-ServiceId-c580d239-b913-41b9-936b-b2d2acb5d3de',
    'IBM_API_KEY_ID': '1VLoW-85sGYJZJwMyy3KzjWFMRy7I0lGKQM82tJ2mFiL',
    'ENDPOINT': 'https://s3.private.eu.cloud-object-storage.appdomain.cloud',
    'IBM_AUTH_ENDPOINT': 'https://iam.cloud.ibm.com/oidc/token',
    'BUCKET': 'datapreprocessing-donotdelete-pr-qtq4gpxztnowyq',
    'FILE': 'Churn_Modelling.csv'
}


In [3]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.

if os.environ.get('RUNTIME_ENV_LOCATION_TYPE') == 'external':
    endpoint_4dbd5f4eb53c4b288106239ad3fb5af5 = 'https://s3.eu.cloud-object-storage.appdomain.cloud'
else:
    endpoint_4dbd5f4eb53c4b288106239ad3fb5af5 = 'https://s3.private.eu.cloud-object-storage.appdomain.cloud'

client_4dbd5f4eb53c4b288106239ad3fb5af5 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='1VLoW-85sGYJZJwMyy3KzjWFMRy7I0lGKQM82tJ2mFiL',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url=endpoint_4dbd5f4eb53c4b288106239ad3fb5af5)

body = client_4dbd5f4eb53c4b288106239ad3fb5af5.get_object(Bucket='datapreprocessing-donotdelete-pr-qtq4gpxztnowyq',Key='Churn_Modelling.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

data = pd.read_csv(body)
data.head()



RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0   
1          2    15647311      Hill          225     Spain  Female  41.0   
2          3    15619304      Onio          629    France  Female  42.0   
3          4    15701354      Boni          699    France  Female  39.0   
4          5    15737888  Mitchell          850       NaN  Female  43.0   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
type(data)

pandas.core.frame.DataFrame

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        9999 non-null   object 
 5   Gender           9999 non-null   object 
 6   Age              9999 non-null   float64
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB


In [6]:
#statstical analysis
data.describe()

RowNumber    CustomerId  CreditScore          Age        Tenure  \
count  10000.00000  1.000000e+04  10000.00000  9999.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.48290    38.924892      5.012800   
std     2886.89568  7.193619e+04     96.72014    10.486670      2.892174   
min        1.00000  1.556570e+07    225.00000    18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.00000    32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.00000    37.000000      5.000000   
75%     7500.25000  1.575323e+07    717.25000    44.000000      7.000000   
max    10000.00000  1.581569e+07    850.00000    92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76489.148004       1.530200      0.70550        0.515100   
std     62399.589585       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127651.035000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [7]:
data.shape

(10000, 14)

In [8]:
#handling the missing values

In [9]:
data.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography           True
Gender              True
Age                 True
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [10]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          1
Gender             1
Age                1
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [11]:
data["Gender"].unique()

array(['Female', 'Male', nan], dtype=object)

In [12]:
data["Geography"].unique()

array(['France', 'Spain', nan, 'Germany'], dtype=object)

In [13]:
data["Gender"].fillna(data["Gender"].mode()[0],inplace=True)

In [14]:
data.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography           True
Gender             False
Age                 True
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [15]:
data["Geography"].fillna(data["Geography"].mode()[0],inplace=True)

In [16]:
data["Age"].fillna(data["Age"].mean(),inplace=True)

In [17]:
data.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["Geography"]=le.fit_transform(data["Geography"])
data["Gender"]=le.fit_transform(data["Gender"])

In [19]:
data


RowNumber  CustomerId    Surname  CreditScore  Geography  Gender   Age  \
0             1    15634602   Hargrave          619          0       0  42.0   
1             2    15647311       Hill          225          2       0  41.0   
2             3    15619304       Onio          629          0       0  42.0   
3             4    15701354       Boni          699          0       0  39.0   
4             5    15737888   Mitchell          850          0       0  43.0   
...         ...         ...        ...          ...        ...     ...   ...   
9995       9996    15606229   Obijiaku          771          0       1  39.0   
9996       9997    15569892  Johnstone          516          0       1  35.0   
9997       9998    15584532        Liu          709          0       0  36.0   
9998       9999    15682355  Sabbatini          772          1       1  42.0   
9999      10000    15628319     Walker          792          0       0  28.0   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [20]:
x=data.iloc[:,3:13].values
y=data.iloc[:,13:14].values


In [21]:
x


array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [22]:
y

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]])

In [23]:
type(x)

numpy.ndarray

In [24]:
x.shape

(10000, 10)

In [25]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
z=one.fit_transform(x[:,1:2]).toarray()

In [26]:
    z

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [27]:
x=np.delete(x,1,axis=1)
x

array([[6.1900000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 0.0000000e+00, 4.1000000e+01, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 3.6000000e+01, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 2.8000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [28]:
x.shape

(10000, 9)

In [29]:
x=np.concatenate((z,x),axis=1)

In [30]:
x

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [31]:
x.shape

(10000, 12)

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=0)

In [34]:
x.shape

(10000, 12)

In [35]:
x_train.shape

(8000, 12)

In [36]:
x_test.shape

(2000, 12)

In [37]:
from sklearn.model_selection import train_test_split
x1=[1,2,3,4,5,6,7,8,9,10]
y1=[1,0,1,0,1,0,1,0,1,0]
for i in range(5):
    x_train1,x_test1,y_train1,y_test1=train_test_split(x1,y1,test_size=0.2,random_state=2)
    print(x_train1,"with random state")

[6, 1, 8, 3, 4, 7, 10, 9] with random state
[6, 1, 8, 3, 4, 7, 10, 9] with random state
[6, 1, 8, 3, 4, 7, 10, 9] with random state
[6, 1, 8, 3, 4, 7, 10, 9] with random state
[6, 1, 8, 3, 4, 7, 10, 9] with random state


In [38]:
for i in range(5):
    x_train1,x_test1,y_train1,y_test1=train_test_split(x1,y1,test_size=0.2)
    print(x_train1,"without random state")

[5, 9, 4, 1, 10, 2, 8, 7] without random state
[10, 1, 9, 7, 5, 2, 8, 6] without random state
[4, 8, 5, 6, 9, 2, 1, 3] without random state
[5, 10, 6, 8, 1, 4, 2, 7] without random state
[9, 10, 7, 5, 3, 4, 6, 8] without random state


In [39]:
from sklearn.ensemble import RandomForestClassifier
forest_reg=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=42)
forest_reg.fit(x_train,y_train)

/tmp/wsuser/ipykernel_156/4171938627.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  forest_reg.fit(x_train,y_train)


RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=42)

In [40]:
x_train[0]

array([0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 6.6700000e+02,
       0.0000000e+00, 3.4000000e+01, 5.0000000e+00, 0.0000000e+00,
       2.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.6383064e+05])

In [41]:
pip install ibm_watson_machine_learning

Note: you may need to restart the kernel to use updated packages.


In [42]:
from ibm_watson_machine_learning import APIClient
wml_credentials={"url":"https://eu-gb.ml.cloud.ibm.com",
                "apikey":"QN45BrPwmUWbPT0dPGYKk6761QcooinTgfBQVzJjFGzD"}
client=APIClient(wml_credentials)

In [43]:
#to create deployment space in ibm cloud
def guid_from_space_name(client, space_name):
    space=client.spaces.get_details()
    #print(spaces)
    return(next(item for item in space['resources'] if item['entity']["name"] == space_name)['metadata']['id'])

In [44]:
space_uid=guid_from_space_name(client, 'NewSpace')
print("Space UID = " + space_uid)

Space UID = 01691062-56af-433d-87dd-ca261afe8151


In [45]:
client.set.default_space(space_uid)

'SUCCESS'

In [46]:
client.software_specifications.list()

-----------------------------  ------------------------------------  ----
NAME                           ASSET_ID                              TYPE
default_py3.6                  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
pytorch-onnx_1.3-py3.7-edt     069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6        09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12     09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
ai-function_0.1-py3.6          0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                     0e6e79df-875e-4f24-8ae9-62dcc2148306  base
tensorflow_2.4-py3.7-horovod   1092590a-307d-563d-9b62-4eb7d64b3f22  base
pytorch_1.1-py3.6              10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl      111e41b3-de2d-5422-a4d6-bf776828c4b7  base
scikit-learn_0.22-py3.6        154010fa-5b3b-4ac1-82af-4d5ee5abbc85  base
default_r3.6                   1b70aec3-ab34-4b87-8aa0-a4a3c8296a36  base
pytorch-onnx_1.3-py3.6         1bc6029

In [62]:
software_spec_uid=client.software_specifications.get_uid_by_name("default_py3.8")
software_spec_uid

'ab9e1b80-f2ce-592c-a7d2-4f2344f77194'

In [63]:
model_details = client.repository.store_model(model=forest_reg,meta_props={
    client.repository.ModelMetaNames.NAME:"Churn_modeling",
    client.repository.ModelMetaNames.TYPE:"scikit-learn_0.23",
    client.repository.ModelMetaNames.SOFTWARE_SPEC_UID:software_spec_uid})

model_id=client.repository.get_model_uid(model_details)

In [64]:
model_id

'fcebdb65-b23a-4dca-88a5-81c4da1b5e0d'

In [65]:
x_train[0]

array([0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 6.6700000e+02,
       0.0000000e+00, 3.4000000e+01, 5.0000000e+00, 0.0000000e+00,
       2.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.6383064e+05])

In [68]:
forest_reg.predict([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 6.6700000e+02,
       0.0000000e+00, 3.4000000e+01, 5.0000000e+00, 0.0000000e+00,
       2.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.6383064e+05]])

array([0])